
name: publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "offlineMode" branch
  push:
    branches: [ "offlineMode" ]
  pull_request:
    branches: [ "offlineMode" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # build job
  build:
    runs-on: ubuntu-latest
    steps:
      # copies into $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          ref: 'offlineMode'
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Setup
        run: |
          cargo install wasm-pack
          npm --prefix $GITHUB_WORKSPACE/frontend ci
      - name: Build
        run: |
          npm --prefix $GITHUB_WORKSPACE/frontend run buildOffline
          mkdir ./_site
          cp -r $GITHUB_WORKSPACE/frontend/dist ./_site
          ls -lh ./_site/dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: 'github-pages'
          path: ./_site/dist
          if-no-files-found: error

  # deploy job
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4

      
